twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/custom_layout.html.twig']
#    form_themes: ['tailwind_2_layout.html.twig']
#    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
