<?php

namespace App\Controller\Admin;

use App\Entity\GameDay;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class GameDayCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return GameDay::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setPaginatorPageSize(25)
            ;
    }

    public function configureFilters(Filters $filters): Filters
    {
        return $filters
            ->add('title')
            ->add('year')
            ->add('day')
            ->add('active')
            ;
//        return parent::configureFilters($filters); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
//        return [
//            IdField::new('id')->hideOnForm(),
//            TextField::new('title'),
////            TextEditorField::new('description'),
//        ];
        yield AssociationField::new('year');
        yield AssociationField::new('day');
        yield TextField::new('title');
        yield BooleanField::new('active');
    }

}
